const dummyDataEvent = [
 {
  id: 1,
  eventName: 'Bukber',
  description: 'Buka bersama',
  date: '20-02-2024',
  location: 'Jakarta',
  startTime: '18:00',
  endTime: '21:00',
  organizer: 'Community',
  contactOrganizer: 'contact@community.com',
  presenter: 'John Doe',
  picture: 'https://example.com/image1.jpg',
  status: 'Published',
 },
 {
  id: 2,
  eventName: 'Seminar',
  description: 'Seminar tentang teknologi',
  date: '25-02-2024',
  location: 'Bandung',
  startTime: '10:00',
  endTime: '16:00',
  organizer: 'Tech Event Organizer',
  contactOrganizer: 'contact@techevent.com',
  presenter: 'Jane Doe',
  picture: 'https://example.com/image3.jpg',
  status: 'Draft',
 },
 {
  id: 3,
  eventName: 'Webinar',
  description: 'Webinar tentang pemasaran digital',
  date: '10-03-2024',
  location: 'Online',
  startTime: '14:00',
  endTime: '16:00',
  organizer: 'Digital Marketing Club',
  contactOrganizer: 'contact@digitalmarketingclub.com',
  presenter: 'John Smith',
  picture: 'https://example.com/image4.jpg',
  status: 'Published',
 },
 {
  id: 4,
  eventName: 'Webinar',
  description: 'Webinar tentang pemasaran digital',
  date: '10-03-2024',
  location: 'Online',
  startTime: '14:00',
  endTime: '16:00',
  organizer: 'Digital Marketing Club',
  contactOrganizer: 'contact@digitalmarketingclub.com',
  presenter: 'John Smith',
  picture: 'https://example.com/image4.jpg',
  status: 'Published',
 },
 {
  id: 5,
  eventName: 'Webinar',
  description: 'Webinar tentang pemasaran digital',
  date: '10-03-2024',
  location: 'Online',
  startTime: '14:00',
  endTime: '16:00',
  organizer: 'Digital Marketing Club',
  contactOrganizer: 'contact@digitalmarketingclub.com',
  presenter: 'John Smith',
  picture: 'https://example.com/image4.jpg',
  status: 'Published',
 },
 {
  id: 6,
  eventName: 'Webinar',
  description: 'Webinar tentang pemasaran digital',
  date: '10-03-2024',
  location: 'Online',
  startTime: '14:00',
  endTime: '16:00',
  organizer: 'Digital Marketing Club',
  contactOrganizer: 'contact@digitalmarketingclub.com',
  presenter: 'John Smith',
  picture: 'https://example.com/image4.jpg',
  status: 'Published',
 },
 {
  id: 7,
  eventName: 'Webinar',
  description: 'Webinar tentang pemasaran digital',
  date: '10-03-2024',
  location: 'Online',
  startTime: '14:00',
  endTime: '16:00',
  organizer: 'Digital Marketing Club',
  contactOrganizer: 'contact@digitalmarketingclub.com',
  presenter: 'John Smith',
  picture: 'https://example.com/image4.jpg',
  status: 'Published',
 },
 {
  id: 8,
  eventName: 'Webinar',
  description: 'Webinar tentang pemasaran digital',
  date: '10-03-2024',
  location: 'Online',
  startTime: '14:00',
  endTime: '16:00',
  organizer: 'Digital Marketing Club',
  contactOrganizer: 'contact@digitalmarketingclub.com',
  presenter: 'John Smith',
  picture: 'https://example.com/image4.jpg',
  status: 'Published',
 },
 {
  id: 9,
  eventName: 'Webinar',
  description: 'Webinar tentang pemasaran digital',
  date: '10-03-2024',
  location: 'Online',
  startTime: '14:00',
  endTime: '16:00',
  organizer: 'Digital Marketing Club',
  contactOrganizer: 'contact@digitalmarketingclub.com',
  presenter: 'John Smith',
  picture: 'https://example.com/image4.jpg',
  status: 'Published',
 },
 {
  id: 10,
  eventName: 'Webinar',
  description: 'Webinar tentang pemasaran digital',
  date: '10-03-2024',
  location: 'Online',
  startTime: '14:00',
  endTime: '16:00',
  organizer: 'Digital Marketing Club',
  contactOrganizer: 'contact@digitalmarketingclub.com',
  presenter: 'John Smith',
  picture: 'https://example.com/image4.jpg',
  status: 'Published',
 },
 {
  id: 11,
  eventName: 'Webinar',
  description: 'Webinar tentang pemasaran digital',
  date: '10-03-2024',
  location: 'Online',
  startTime: '14:00',
  endTime: '16:00',
  organizer: 'Digital Marketing Club',
  contactOrganizer: 'contact@digitalmarketingclub.com',
  presenter: 'John Smith',
  picture: 'https://example.com/image4.jpg',
  status: 'Published',
 },
 {
  id: 12,
  eventName: 'Webinar',
  description: 'Webinar tentang pemasaran digital',
  date: '10-03-2024',
  location: 'Online',
  startTime: '14:00',
  endTime: '16:00',
  organizer: 'Digital Marketing Club',
  contactOrganizer: 'contact@digitalmarketingclub.com',
  presenter: 'John Smith',
  picture: 'https://example.com/image4.jpg',
  status: 'Published',
 },
 {
  id: 13,
  eventName: 'Webinar',
  description: 'Webinar tentang pemasaran digital',
  date: '10-03-2024',
  location: 'Online',
  startTime: '14:00',
  endTime: '16:00',
  organizer: 'Digital Marketing Club',
  contactOrganizer: 'contact@digitalmarketingclub.com',
  presenter: 'John Smith',
  picture: 'https://example.com/image4.jpg',
  status: 'Published',
 },
 {
  id: 14,
  eventName: 'Webinar',
  description: 'Webinar tentang pemasaran digital',
  date: '10-03-2024',
  location: 'Online',
  startTime: '14:00',
  endTime: '16:00',
  organizer: 'Digital Marketing Club',
  contactOrganizer: 'contact@digitalmarketingclub.com',
  presenter: 'John Smith',
  picture: 'https://example.com/image4.jpg',
  status: 'Published',
 },
];

export default dummyDataEvent;
